import Screen from '@/components/Screen';
import Head from 'next/head'
import Navbar from "../components/Navbar";

export default function Home() {

  /** This project is intended to just to learn and explore my creativity on the animation side of UI  */
  /**  Hence why the codes are not clean */

  return (
    <>
      <Head>
        <title>Nocurves</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://cdn.pixabay.com/photo/2016/07/11/17/45/abstract-1510190_960_720.png" />
      </Head>
      <header>
         <Navbar/>
      </header> 
      <main>
         <Screen/>
      </main>
      <footer>
        
      </footer>
    </>
  )
}
